### ISSUE TITLE
UX/UI_Day reports: All '+' buttons ( 'Add tag', 'Show all statistic', 'Add job', 'Add plan', etc. ) are asymmetrical

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#760]
## Steps to reproduce

1. Open any day report.
2. Check all '+' buttons ('Add tag', 'Show all statistic', 'Add job', 'Add plan', etc. ).

## Actual result

'+' buttons are asymmetrical. 

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/07f69118-2f66-4bbc-a5e3-89c9c6109671)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/f9f7c2d8-e561-46a9-86b8-f99eb2aaabae)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/ff589f91-eb0a-4aee-bf17-b937857715f7)

**Comment by algrinkevich** [comment]
@EkaterinaSokolova-V I can't reproduce it. Could you please check it?

**Comment by EkaterinaSokolova-V** [comment]
@algrinkevich, looks like it was fixed earlier.
Closed.

**Comment by algrinkevich** [comment]
@EkaterinaSokolova-V Have you ability to check it locally? Branch `MW-760/plus-buttons-are-asymmetrical`. I made some changes basing on my thoughts, because it's not reproduced on my laptop. I think this is due to the specifics of my display.

<img src="https://github.com/tritonJS826/masters-way/assets/8752900/975a8eed-f838-4ec0-b960-a2873a1bbdb9" width="900"/>

<img src="https://github.com/tritonJS826/masters-way/assets/8752900/3d36d6fe-92c3-49ad-9e82-f3cf83e0eb7b" width="500" />

**Comment by EkaterinaSokolova-V** [comment]
fixed
