### ISSUE TITLE
user's ways: Only last tag displayed on the all Ways page in card view

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#937]
## Description

Only last tag displayed on the [All ways page](https://mastersway.netlify.app/ways).
At the same time on User page all Way tags is displayed.

## Preconditions

1. Create Way
2. Set for Way more than one tag
![image](https://github.com/tritonJS826/masters-way/assets/4976837/f3942ff8-27f3-406c-91c9-d3c192427287)

## Steps to reproduce

1. Open [All ways page](https://mastersway.netlify.app/ways)
2. Switch to [card view](https://github.com/tritonJS826/masters-way/assets/4976837/264b2d0b-bfee-46e1-ab7b-43ea9dfe60ac)

## Actual result

Only last tag displayed on the [All ways page](https://mastersway.netlify.app/ways).
![image](https://github.com/tritonJS826/masters-way/assets/4976837/34e68e6c-5bbb-414e-a969-4ded52694ed8)

## Expected result

All Way tags is displayed
![image](https://github.com/tritonJS826/masters-way/assets/4976837/2585a113-d47d-4bfe-9e06-cb6213cf518b)

**Comment by algrinkevich** [comment]
This is a response from "GET /ways" endpoint. It returns only 1 wayTag from specific way.
<img src="https://github.com/tritonJS826/masters-way/assets/8752900/630b6580-d858-4663-bc18-097019dcb21a" width="700"/>

When I call an API for getting the same way, the server returns all 3 tags.
<img src="https://github.com/tritonJS826/masters-way/assets/8752900/262d2209-5ec4-4764-af01-37a2abc1f3e9" width="700" />

@tritonJS826 It looks like the backend issue, otherwise I need to call an API for getting the tags for each way card on the page.

**Comment by algrinkevich** [comment]
It seems that the issue is not reproduced anymore. @pp2amd6 Could you please check it again?

**Comment by pp2amd6** [comment]
> It seems that the issue is not reproduced anymore. @pp2amd6 Could you please check it again?

Yeap, not reproduce anymore
